// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonstersSA.Web.Data;

#nullable disable

namespace MonstersSA.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203053520_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MonstersSA.Web.Models.PlayedTournament", b =>
                {
                    b.Property<long>("PlayedTournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetResult")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBuyIn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalPayout")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TournamentDefinitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayedTournamentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("TournamentDefinitionId");

                    b.ToTable("PlayedTournaments", (string)null);
                });

            modelBuilder.Entity("MonstersSA.Web.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("MonstersSA.Web.Models.StatementFile", b =>
                {
                    b.Property<int>("StatementFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadDateUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("StatementFileId");

                    b.HasIndex("PlayerId");

                    b.ToTable("StatementFiles", (string)null);
                });

            modelBuilder.Entity("MonstersSA.Web.Models.TournamentDefinition", b =>
                {
                    b.Property<int>("TournamentDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuyInAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TournamentDefinitionId");

                    b.ToTable("TournamentDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            TournamentDefinitionId = 1,
                            BuyInAmount = 5.50m,
                            Name = "MICRO ROLLER",
                            StartTime = new TimeOnly(23, 34, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 2,
                            BuyInAmount = 5.50m,
                            Name = "MICRO NIGHTLY",
                            StartTime = new TimeOnly(1, 54, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 3,
                            BuyInAmount = 11.00m,
                            Name = "LUCKY 7s",
                            StartTime = new TimeOnly(0, 20, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 4,
                            BuyInAmount = 11.00m,
                            Name = "CRAZY 8s",
                            StartTime = new TimeOnly(14, 30, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 5,
                            BuyInAmount = 11.00m,
                            Name = "CRAZY KO",
                            StartTime = new TimeOnly(23, 10, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 6,
                            BuyInAmount = 16.50m,
                            Name = "LOW ROLLER",
                            StartTime = new TimeOnly(22, 34, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 7,
                            BuyInAmount = 16.50m,
                            Name = "CRAZY 8s MADRUGADA",
                            StartTime = new TimeOnly(2, 10, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 8,
                            BuyInAmount = 9.90m,
                            Name = "MINOR NINER",
                            StartTime = new TimeOnly(3, 40, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 9,
                            BuyInAmount = 9.90m,
                            Name = "EARLY NINER",
                            StartTime = new TimeOnly(15, 30, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 10,
                            BuyInAmount = 4.40m,
                            Name = "MICRO MONSTER",
                            StartTime = new TimeOnly(1, 10, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 11,
                            BuyInAmount = 55.00m,
                            Name = "NIGHTLY",
                            StartTime = new TimeOnly(2, 30, 0)
                        },
                        new
                        {
                            TournamentDefinitionId = 12,
                            BuyInAmount = 0.00m,
                            Name = "FREEROLL",
                            StartTime = new TimeOnly(0, 0, 0)
                        });
                });

            modelBuilder.Entity("MonstersSA.Web.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CashAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatementFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("StatementFileId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("MonstersSA.Web.Models.PlayedTournament", b =>
                {
                    b.HasOne("MonstersSA.Web.Models.Player", "Player")
                        .WithMany("PlayedTournaments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonstersSA.Web.Models.TournamentDefinition", "TournamentDefinition")
                        .WithMany()
                        .HasForeignKey("TournamentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TournamentDefinition");
                });

            modelBuilder.Entity("MonstersSA.Web.Models.StatementFile", b =>
                {
                    b.HasOne("MonstersSA.Web.Models.Player", "Player")
                        .WithMany("StatementFiles")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MonstersSA.Web.Models.Transaction", b =>
                {
                    b.HasOne("MonstersSA.Web.Models.StatementFile", "StatementFile")
                        .WithMany("Transactions")
                        .HasForeignKey("StatementFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatementFile");
                });

            modelBuilder.Entity("MonstersSA.Web.Models.Player", b =>
                {
                    b.Navigation("PlayedTournaments");

                    b.Navigation("StatementFiles");
                });

            modelBuilder.Entity("MonstersSA.Web.Models.StatementFile", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
